[tool.poetry]
name = "rgt-digital-twin"
version = "0.1.0"
description = ""
authors = ["Jacqueline Lammert <jacqueline.lammert@tum.de>",
            "Max Tschochohei <maxtsc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain-ollama = "^0.3.3"
langchain-community = "^0.3.27"
pypdf = "^5.8.0"
google-genai = "^1.27.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-asyncio = "^1.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
